spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  resources:
    add-mappings: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

comment.avatar: images/avatar.jpeg